cfg:
  train_ds:
    manifest_filepath: ./train.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - x
    - 'y'
    - z
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    num_workers: 8
    pin_memory: true
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: synced_randomized
    bucketing_batch_size: null
  validation_ds:
    manifest_filepath: ./test.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - x
    - 'y'
    - z
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - ''''
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: per_feature
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: hann
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
    stft_conv: false
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 64
    activation: relu
    conv_mask: true
    jasper:
    - filters: 128
      repeat: 1
      kernel:
      - 11
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 256
      repeat: 1
      kernel:
      - 13
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 256
      repeat: 1
      kernel:
      - 15
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 256
      repeat: 1
      kernel:
      - 17
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 256
      repeat: 1
      kernel:
      - 19
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: true
      separable: true
      se: true
      se_context_size: -1
    - filters: 256
      repeat: 1
      kernel:
      - 21
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 1024
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 1024
    num_classes: 31
    vocabulary:
    - ' '
    - a
    - b
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - x
    - 'y'
    - z
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - ''''
  optim:
    name: novograd
    lr: 0.01
    betas:
    - 0.8
    - 0.5
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      monitor: val_loss
      reduce_on_plateau: false
      warmup_steps: null
      warmup_ratio: null
      min_lr: 0.0
      last_epoch: -1
  target: nemo.collections.asr.models.ctc_models.EncDecCTCModel
  nemo_version: 1.20.0
